### ISSUE TITLE
How to enable session compression to reduce cookie size?

### ISSUE THREAD

**Issue by bigbugbean** [revomatico/docker-kong-oidc#17]
Hi, I already set the environment variable  `KONG_X_SESSION_COMPRESSOR=zlib` in my `docker-compose.yml`, but the cookies are still same size,  more than 5000 bytes. Are there any other parameters I need to set?

This is my `docker-compose.yml`
```
version: '3.4'

networks:
  kong-net:

volumes:
  kong-datastore:

services:
  kong-db:
    image: postgres:9.6
    volumes:
      - kong-datastore:/var/lib/postgresql/data
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong

  kong:
    image: revomatico/docker-kong-oidc:2.3.3-1
    volumes:
      - /data/solution/docker/kong/nginx_kong.lua:/usr/local/share/lua/5.1/kong/templates/nginx_kong.lua
      - /data/solution/www:/var/www/
    depends_on:
      - kong-db
    networks:
      - kong-net
    extra_hosts:
      - "sg.digitalgd.com.cn:172.16.0.3"
      - "ywpt.digitalgd.com.cn:172.16.16.43"
    ports:
      - "38000:8000" # Listener
      - "38001:8001" # Admin API
      - "38443:8443" # Listener  (SSL)
      - "38444:8444" # Admin API (SSL)
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS: bundled,oidc
      KONG_X_SESSION_COMPRESSOR: zlib
```
