### ISSUE TITLE
docker-kong-oidx image used with POSTGRES: unable to start

### ISSUE THREAD

**Issue by pixime** [revomatico/docker-kong-oidc#18]
Hello all,

I am desperately trying to use the image with POSTGRES. Here is my docker-compose:

```
kong:
    image: docker-kong-oidc:2.3.3-2
    user: "${KONG_USER:-kong}"
    depends_on:
      - kong-db
    environment:
      - KONG_LOG_LEVEL=info
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_GUI_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_GUI_ERROR_LOG=/dev/stderr
      - KONG_PORTAL_API_ACCESS_LOG=/dev/stdout
      - KONG_PORTAL_API_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ANONYMOUS_REPORTS=false
      - KONG_CLUSTER_LISTEN=off
      - 'KONG_LUA_PACKAGE_PATH=/opt/?.lua;/opt/?/init.lua;;'
      - KONG_NGINX_WORKER_PROCESSES=1
      - 'KONG_PLUGINS=bundled,oidc'
      - 'KONG_ADMIN_LISTEN=0.0.0.0:8001'
      - 'KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 http2 ssl'
      - 'KONG_STATUS_LISTEN=0.0.0.0:8100'
      - KONG_NGINX_DAEMON=off
      - 'KONG_X_SESSION_MEMCACHE_PORT=''1234'''
      - KONG_X_SESSION_COMPRESSOR=zlib
      - KONG_DATABASE=postgres
      - KONG_PG_DATABASE=${KONG_PG_DATABASE:-kong}
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=${KONG_PG_USER:-kong}
      - KONG_PG_PASSWORD_FILE=/run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
```

And there is the output I got from my kong-idc container on start:
```
kong_1                | 2021/04/09 14:42:49 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: New migrations available; run 'kong migrations up' to proceed
kong_1                | stack traceback:
kong_1                |         [C]: in function 'error'
kong_1                |         /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: in function 'check_state'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:456: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
kong_1                | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: New migrations available; run 'kong migrations up' to proceed
kong_1                | stack traceback:
kong_1                |         [C]: in function 'error'
kong_1                |         /usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:20: in function 'check_state'
kong_1                |         /usr/local/share/lua/5.1/kong/init.lua:456: in function 'init'
kong_1                |         init_by_lua:3: in main chunk
compose_kong_1 exited with code 1
```
I tried to use the image in db-less mode and it's work fine.

I also have in my docker-compose.yml services for migrations:

```
kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: kong-db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: kong-db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
```

I have cleaned my POSTGRES volume and down/up many times, but I still got the same results.

I would also like to point out that using the standard version of Kong works fine:

```
image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    depends_on:
      - kong-db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: kong-db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
```

Thanks for your help
