### ISSUE TITLE
is client_credentials flow supported?

### ISSUE THREAD

**Issue by hyt05** [revomatico/docker-kong-oidc#9]
Hello Team,
I was trying to implement the service to service call via plugin authentication.
I expect the plugin will use client_credential grant flow and get me a bearer token which I will use to call the required service. There should not be any user interaction in authentication process. It should be with client id & secret only.

Do you know if plugin supports this behaviour? If yes, can you please help me configure it?

**Comment by cristichiru** [comment]
Hello,

Din not experiment a lot with this, but you could try the following parameters for kong_oidc plugin included in this release, for example:

```yaml
  - hosts:
    - myhost.com
    name: myhost-name
    paths:
    - /api
    preserve_host: true
    strip_path: false
    tags:
    - myapp
    plugins:
    - name: oidc
      config:
        disable_access_token_header: "no"
        access_token_header_as_bearer: "yes"
        access_token_header_name: X-Access-Token
        bearer_only: "yes"
        client_id: client
        client_secret: secret
        disable_id_token_header: "yes"
        disable_userinfo_header: "no"
        discovery: https://authz-server.com/.well-known/openid-configuration
        id_token_header_name: X-ID-Token
        ......
```
